#!/bin/bash

if [ ${#} -ne 1 ]
then
    echo usage csprecon-domains domainFile
    exit
fi

timeAndDate=$(date "+%F %T")
timeAndDate=$(echo ${timeAndDate} | sed 's/ /-T-/g')
timeStamp=$(echo ${timeAndDate} | sed 's/:/-/g')

awk '{print "https://"$0}' ${1} > /tmp/${timeStamp}-new-csphosts.txt

# get active hosts with webserver
csprecon -silent -l /tmp/${timeStamp}-new-csphosts.txt 

