#!/bin/bash

if [ ${#} -ne 1 ]
then
    echo usage get-dns-records.sh domain
    echo "Run dig command for different DNS record types"
    exit
fi

outFile="/tmp/dns-resource-record-result.txt"

dig A ${1} >> ${outFile}
dig AAAA ${1} >> ${outFile}
dig AFSDB ${1} >> ${outFile}
dig APL ${1} >> ${outFile}
dig A6 ${1} >> ${outFile}
dig CAA ${1} >> ${outFile}
dig CDNSKEY ${1} >> ${outFile}
dig CDS ${1} >> ${outFile}
dig CERT ${1} >> ${outFile}
dig CNAME ${1} >> ${outFile}
dig DHCID ${1} >> ${outFile}
dig DLV ${1} >> ${outFile}
dig DNAME ${1} >> ${outFile}
dig DNSKEY ${1} >> ${outFile}
dig DS ${1} >> ${outFile}
dig GPOS ${1} >> ${outFile}
dig HIP ${1} >> ${outFile}
dig HINFO ${1} >> ${outFile}
dig HTTPS ${1} >> ${outFile}
dig IPSECKEY ${1} >> ${outFile}
dig ISDN ${1} >> ${outFile}
dig KEY ${1} >> ${outFile}
dig KX ${1} >> ${outFile}
dig LOC ${1} >> ${outFile}
dig MB ${1} >> ${outFile}
dig MD ${1} >> ${outFile}
dig MF ${1} >> ${outFile}
dig MG ${1} >> ${outFile}
dig MINFO ${1} >> ${outFile}
dig MR ${1} >> ${outFile}
dig MX ${1} >> ${outFile}
dig NAPTR ${1} >> ${outFile}
dig NS ${1} >> ${outFile}
dig NSAP ${1} >> ${outFile}
dig NSEC ${1} >> ${outFile}
dig NSEC3 ${1} >> ${outFile}
dig NSEC3PARAM ${1} >> ${outFile}
dig NULL ${1} >> ${outFile}
dig NXT ${1} >> ${outFile}
dig OPT ${1} >> ${outFile}
dig PTR ${1} >> ${outFile}
dig RP ${1} >> ${outFile}
dig RRSIG ${1} >> ${outFile}
dig SIG ${1} >> ${outFile}
dig SOA ${1} >> ${outFile}
dig SPF ${1} >> ${outFile}
dig SRV ${1} >> ${outFile}
dig SSHFP ${1} >> ${outFile}
dig TA ${1} >> ${outFile}
dig TKEY ${1} >> ${outFile}
dig TLSA ${1} >> ${outFile}
dig TSIG ${1} >> ${outFile}
dig TXT ${1} >> ${outFile}
dig URI ${1} >> ${outFile}
dig WKS ${1} >> ${outFile}
dig X25 ${1} >> ${outFile}

cat ${outFile} | grep -v ";; \|; " | grep -v ";${1}" | sort -u
rm ${outFile}

