#!/bin/bash

if [ ${#} -ne 1 ]
then
    echo usage domainFile
    exit
fi

timeStamp=$(date +"%Y-%m-%d_%T")

while read -r domain
do
    # skip empty lines
    if [ -z "${domain}" ]
    then
        continue
    fi

    echo -n "[${domain}]  " >> /tmp/get-copyrights-${timeStamp}
    copyright=$(curl -s -k -L "https://${domain}" | grep -ioE "[-\&;_[:blank:],\.[:alnum:]]*©[-\&;_[:blank:],\.[:alnum:]]*" | python3 -c 'import html,sys; print(html.unescape(sys.stdin.read()), end="")')

    # check for absense of copyright
    if [ -z "${copyright}" ]
    then
        echo "No Copyright" >> /tmp/get-copyrights-${timeStamp}
    else
        echo ${copyright} >> /tmp/get-copyrights-${timeStamp}
    fi

    echo "" >> /tmp/get-copyrights-${timeStamp}
    
    echo "${domain} - done"
done < ${1}

echo ""
echo "#################"
echo ""

sed -i '/^[[:space:]]*$/d' /tmp/get-copyrights-${timeStamp}
sed -i '/^[[:space:]]*$/d' /tmp/get-copyrights-${timeStamp}
sed -i '/©/!d' /tmp/get-copyrights-${timeStamp}
cat /tmp/get-copyrights-${timeStamp} | awk -F "]" '{print $2" "$1"]"}' | sed 's/[ ][ ]*/ /g' | sort

rm /tmp/get-copyrights-${timeStamp}

