#!/usr/bin/env python3

from selenium import webdriver
from selenium.webdriver.firefox.options import Options as FirefoxOptions
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.service import Service
import sys
import urllib.parse
import time
from os import path

if (len(sys.argv) != 2):
    print("usage: {} companyName".format(sys.argv[0]))
    sys.exit(1)

options = FirefoxOptions()
options.add_argument("--ignore-ssl-errors=yes")
options.add_argument('--ignore-certificate-errors')
options.set_preference("network.http.redirection-limit", 4)
options.add_argument("--headless")
service = Service(log_path=path.devnull)
driver = webdriver.Firefox(options=options, service=service)
driver.set_page_load_timeout(40)

# encode
encodedCompany = urllib.parse.quote(sys.argv[1])

url = "https://bgp.he.net/search?search[search]=" + encodedCompany
try:
    driver.get(url)
    
    time.sleep(5)
    
    hrefs = driver.find_elements(By.XPATH, "//a[@href]")
    
    for ref in hrefs:
        if ("AS" in ref.get_attribute("href")):
            newUrl = ref.get_attribute("href") + "#_prefixes"
            break
    
    driver.get(ref.get_attribute("href") + "#_prefixes")
    time.sleep(5)
    ranges = driver.find_elements(By.XPATH, "//a[@href]")
    
    for rangeElement in ranges:
        ran = rangeElement.get_attribute("href")
        if (ran is not None):
            if ("/net/" in ran):
                print(ran.replace("https://bgp.he.net/net/",""))
except:
    print("Error getting: https://bgp.he.net/search?search[search]=" + encodedCompany)

driver.close()

