#!/bin/bash

if [ ${#} -ne 1 ]
then
    echo "usage: ${0} domainFile"
    exit 1
fi

while read -r domain || [[ -n "${domain}" ]]
do
    curl -s -k -L "${domain}" | grep "<title>" | head -n 1 | awk -F "<title>" '{print $2}' | awk -v dom="${domain}" -F "</title>" '{print $1" ["dom"]"}'
done < ${1}

