#!/bin/bash

if [ ${#} -ne 1 ]
then
    echo usage urlFile
    exit
fi

while read -r url
do
    echo -n "[${url}]  "
    curl -s -k -L ${url} | grep -ioE "[-\&;_[:blank:],\.[:alnum:]]*©[-\&;_[:blank:],\.[:alnum:]]*" | python3 -c 'import html,sys; print(html.unescape(sys.stdin.read()), end="")'
	echo ""
done < ${1}

