#!/usr/bin/env python3

from selenium import webdriver                        
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options as FirefoxOptions
import urllib.parse
import datetime
import sys
import time
import os

# check amount of passed arguments
if (len(sys.argv) != 2):
    print("usage: {} companName ".format(sys.argv[0]))
    sys.exit(1)

options = FirefoxOptions()
options.add_argument("--headless")
driver = webdriver.Firefox(options=options)

url = "https://grep.app/search?q=" + urllib.parse.quote(sys.argv[1])
driver.get(url)

time.sleep(5)

# alternative
timestamp = datetime.datetime.today().strftime("%d-%m-%Y_%H:%M:%S")
tempFile = "/tmp/" + timestamp

repos = driver.find_elements(By.XPATH, './/span[@class = "facet-value facet-value-repo"]')

for r in repos:
    innerContent = "https://github.com/" + r.get_attribute("innerHTML")
    os.system("echo " + innerContent + " | tr -cd '\\11\\12\\40-\\176'")

driver.close()

