#!/usr/bin/env python3

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
import sys
import time

if (len(sys.argv) != 2):
    print("usage: {} domain".format(sys.argv[0]))
    sys.exit(1)

options = webdriver.ChromeOptions()
options.add_argument("headless")
driverPath = Service("REPLACEMEDRIVER")
driver = webdriver.Chrome(service = driverPath, options = options)

driver.get("https://phonebook.cz")
time.sleep(3)

textField = driver.find_element_by_id("domain")
textField.send_keys(sys.argv[1])
time.sleep(1)
textField.send_keys(Keys.RETURN)
time.sleep(1)
driver.find_element_by_id("submit1").click()
time.sleep(2)
atags = driver.find_element_by_id("result").find_elements_by_tag_name("a")

for t in atags:
    if (sys.argv[1] in t.get_attribute("innerHTML")):
        print(t.get_attribute("innerHTML"))

driver.close()

