#!/usr/bin/env python3

from os import path
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.options import Options as FirefoxOptions
from selenium.webdriver.firefox.service import Service
import sys
import time

# check amount of passed arguments
if (len(sys.argv) != 2):
    print("usage: {} gid".format(sys.argv[0]))
    print("ID can either be Google Adsense (pub-X) or Google Analytics (ua-X)")
    print("Visit hackertarget.com and extract domains related to google id")
    sys.exit(1)

options = FirefoxOptions()

# headless mode
options.add_argument("--headless")

# certificate errors
options.add_argument("--ignore-ssl-errors=yes")
options.add_argument('--ignore-certificate-errors')

# user agent
options.set_preference("general.useragent.override", "Safari: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.3 (KHTML, like Gecko) Version/11.1 Safari/605.1.3")

# prevent creation of geckodriver.log
service = Service(log_path=path.devnull)
driver = webdriver.Firefox(options=options, service=service)

# 6 seconds timeout
driver.set_page_load_timeout(6)

# 5 seconds default wait for element to be clickable
driver.implicitly_wait(5)

url = "https://hackertarget.com/reverse-analytics-search"
driver.get(url)

time.sleep(2)

# enter google id
input_field = driver.find_element(By.NAME, "theinput")
search_query = sys.argv[1]
input_field.send_keys(search_query)

# submit
submit_button = driver.find_element(By.XPATH, "//button[@type='submit' and contains(@class, 'btnx')]")
submit_button.click()

time.sleep(2)

# print result
responses = driver.find_elements(By.XPATH, "//pre[@id='formResponse']")

for res in responses:
    print(res.get_attribute("innerHTML"))

driver.close()

