#!/bin/bash

if [ ${#} -ne 1 ]
then
    echo usage hakrawler-on-range ipRange
    exit
fi

timeAndDate=$(date "+%F %T")
timeAndDate=$(echo ${timeAndDate} | sed 's/ /-T-/g')
timeStamp=$(echo ${timeAndDate} | sed 's/:/-/g')

nmap -sT -Pn ${1} -n -p 80,443 --open -oG "/tmp/${timeStamp}-nmap-out"

# get active hosts with webserver
grep "Ports" /tmp/${timeStamp}-nmap-out | awk -F " " '{print $2" "$5}' | cut -d "/" -f 1 > /tmp/${timeStamp}-grep-out
 
while read -r line 
do
    ip=$(echo ${line} | cut -d " " -f 1)
    # if str1 contains str2 substring
    if [[ ${line} == *" 80"* ]]
    then
        echo "http://${ip}" | hakrawler -u -s -insecure
    else
        echo "https://${ip}" | hakrawler -u -s -insecure
    fi
done < /tmp/${timeStamp}-grep-out

rm /tmp/${timeStamp}-grep-out

