#!/usr/bin/env python3

import sys
import time
from selenium import webdriver
from selenium.webdriver.firefox.options import Options as FirefoxOptions
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

# check amount of passed arguments
if (len(sys.argv) != 2):
    print("usage: {} copyright".format(sys.argv[0]))
    sys.exit(1)

options = FirefoxOptions()
options.add_argument("--headless")
driver = webdriver.Firefox(options=options)

url = "https://www.google.com/search?q=%22" + sys.argv[1] + "%22"
driver.get(url)
time.sleep(4)

WebDriverWait(driver,5).until(EC.element_to_be_clickable((By.ID, "L2AGLb"))).click()

# send global keydown arrow
actions = ActionChains(driver)
actions.send_keys(Keys.END).perform()
time.sleep(4)

elems = driver.find_elements(By.XPATH, "//a[@href]")
for elem in elems:
    hrefContent = elem.get_attribute("href")
    if ("google" in hrefContent) or ("javascript" in hrefContent):
        continue
    else:
        print(elem.get_attribute("href"))

url = "https://www.google.com/search?q=%22" + sys.argv[1] + "%22&start=10"

driver.get(url)
time.sleep(4)

elems = driver.find_elements(By.XPATH, "//a[@href]")
for elem in elems:
    hrefContent = elem.get_attribute("href")
    if ("google" in hrefContent) or ("javascript" in hrefContent):
        continue
    else:
        print(elem.get_attribute("href"))

driver.close()

